name: Slack notification

on: workflow_call

jobs:  
  slack-notify:
      name: Post Workflow Status To Slack
      runs-on: ubuntu-latest
      permissions:
        actions: 'read'
      steps:
        - name: Slack Workflow Notification
          uses: Gamesight/slack-workflow-status@master
          with:
            repo_token: ${{secrets.GITHUB_TOKEN}}
            slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
            channel: '#github-notifications'
            name: 'Failed GitHub Workflow'
            icon_url: 'https://avatars0.githubusercontent.com/u/1701160?s=96&v=4'
            
